apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ponto-eletronico-api
  labels:
    app: ponto-eletronico-api
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: default-rate-limit@kubernetescrd
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - api.criptoai.io
      secretName: api-criptoai-io-tls
  rules:
    - host: api.criptoai.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ponto-eletronico-api
                port:
                  number: 80
