name: "2 - Deploy ArgoCD"

on:
  workflow_run:
    workflows: ["1 - Build & Push Docker"]
    types: [completed]

jobs:
  deploy:
    name: Sync & Validate
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Install ArgoCD CLI
        run: |
          curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv argocd /usr/local/bin/

      - name: Login no ArgoCD
        run: |
          argocd login ${{ secrets.ARGOCD_SERVER }} \
            --username admin \
            --password '${{ secrets.ARGOCD_AUTH_TOKEN }}' \
            --insecure \
            --grpc-web

      - name: Sync da Application
        run: |
          argocd app sync ponto-eletronico-api \
            --grpc-web \
            --force \
            --prune

      - name: Aguardar deploy saud√°vel
        run: |
          argocd app wait ponto-eletronico-api \
            --grpc-web \
            --health \
            --timeout 300

      - name: Status final
        if: always()
        run: |
          argocd app get ponto-eletronico-api --grpc-web || true
